AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Aptitude
  TODO: Description Here 
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AptitudeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AptitudeLambdaTokenAuthorizer
        Authorizers:
          AptitudeLambdaTokenAuthorizer:
            FunctionArn: !GetAtt AptitudeAuthFunction.Arn

  AptitudeAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.handler
      Runtime: nodejs14.x

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: app.getUser
      Runtime: nodejs14.x
      Events:
        GetUser:
          Type: Api 
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /user/{id}
            Method: GET
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref UserTable

  EditProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: app.editProfile
      Runtime: nodejs14.x
      Events:
        EditProfile:
          Type: Api 
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /user/{id}
            Method: PUT
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref UserTable

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: app.signup
      Runtime: nodejs14.x
      Events:
        Signup:
          Type: Api 
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /user
            Method: POST
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref UserTable

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: app.deleteUser
      Runtime: nodejs14.x
      Events:
        DeleteUser:
          Type: Api 
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /user/{id}
            Method: DELETE
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref UserTable

  GetQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: question/
      Handler: app.getQuestion
      Runtime: nodejs14.x
      Events:
        GetQuestion:
          Type: Api
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /question
            Method: GET
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref QuestionTable
  GetQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: question/
      Handler: app.getQuestions
      Runtime: nodejs14.x
      Events:
        GetQuestions:
          Type: Api
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /questions
            Method: GET
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref QuestionTable
  CreateQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: question/
      Handler: app.createQuestion
      Runtime: nodejs14.x
      Events:
        CreateQuestion:
          Type: Api
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /question
            Method: POST
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref QuestionTable  
  EditQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: question/
      Handler: app.editQuestion
      Runtime: nodejs14.x
      Events:
        EditQuestion:
          Type: Api
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /question/{id}
            Method: PUT
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref QuestionTable
  DeleteQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: question/
      Handler: app.deleteQuestion
      Runtime: nodejs14.x
      Events:
        DeleteQuestion:
          Type: Api
          Properties:
            RestApiId: !Ref AptitudeApi
            Path: /question
            Method: DELETE
            Auth:
              Authorizer: NONE
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref QuestionTable



  # dynamodb
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: user
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  QuestionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: question
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 


Outputs:
  ApiUrl:
      Description: The target URL of the created API
      Value: !Sub "https://${AptitudeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
      Export:
        Name: ApiUrl